[package]
name = "cc2600"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
env_logger = "0.9.1"
log = "0.4"
pest = "2.4"
pest_derive = "2.4"
regex = "1.6"
