[package]
name = "cc2600"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest="2.4"
pest_derive="2.4"
regex="1.6"
